import { Request, Response } from "express";
import { IOtpService } from "../interfaces/serviceInterface/IOtpServerces";
import { TOtp } from "../types/otp";
import {
  ERROR_MESSAGES,
  HTTP_STATUS,
  SUCCESS_MESSAGES,
} from "../shared/constant";
import { CustomError } from "../utils/custom.error";

export class OtpController {
  constructor(private readonly _otpService: IOtpService) {}

  async otpGenerate(req: Request, res: Response): Promise<void> {
    try {
      const data: TOtp = req.body;

      await this._otpService.otpGenerate(data);

      res.status(HTTP_STATUS.CREATED).json({
        success: true,
        message: SUCCESS_MESSAGES.OTP_SEND_SUCCESS,
      });

    } catch (error) {
      if (error instanceof CustomError) {
        res.status(error.statusCode).json({
          success: false,
          message: error.message,
        });
        return;
      }

      console.error("[OtpController Error]:", error);

      res.status(HTTP_STATUS.INTERNAL_SERVER_ERROR).json({
        success: false,
        message: ERROR_MESSAGES.SERVER_ERROR,
      });
    }
  }

  async verifyOtpToRegister(req: Request, res: Response) {
    try {
      const data = req.body;

      await this._otpService.verifyOtp(data);
      res.status(HTTP_STATUS.OK).json({
        success: true,
        message: SUCCESS_MESSAGES.VERIFICATION_SUCCESS,
      });
    } catch (error) {
      if (error instanceof CustomError) {
        res
          .status(error.statusCode)
          .json({ success: false, message: error.message });
        return;
      }
      console.log(error);
      res
        .status(HTTP_STATUS.INTERNAL_SERVER_ERROR)
        .json({ success: false, message: ERROR_MESSAGES.SERVER_ERROR });
    }
  }
}
